<?php

namespace DN\PerfectNumber\Helpers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-06-07 at 15:40:24.
 */
class MathTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Math
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Math;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DN\PerfectNumber\Helpers\Math::calcAliquotSum
     * @todo   Implement testCalcAliquotSum().
     * 
     */
    public function testCalcAliquotSum() {


        $this->assertEquals(0, $this->object->calcAliquotSum(1));

        $this->assertEquals(9, $this->object->calcAliquotSum(15));

        $this->assertEquals(9, $this->object->calcAliquotSum(15));
        // Remove the following lines when you implement this test.

        try {
            $this->assertEquals(0, $this->object->calcAliquotSum(0));
        } catch (\Exception $exc) {
            return;
        }
        $this->fail();
    }

}
